apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017 # Get this from mongodb official image
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
           secretKeyRef:
             name: mongodb-secret # the name from the secret file metadata
             key: mongo-root-username # the key being referenced
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
             name: mongodb-secret # the name from the secret file metadata
             key: mongo-root-password # the key being referenced


---
apiVersion: v1
kind: Service
metadata:
  name: mondodb-service
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
